const ActionTypes = {
  FETCH_USER_DATA: "FETCH_USER_DATA",
  EDIT_USER_DATA: "EDIT_USER_DATA",
  FETCH_USER_REPO: "FETCH_USER_REPO",
  FETCH_CONTRIBUTION_DATA: "FETCH_CONTRIBUTION_DATA",
  SET_DAILY_CONTRIBUTION_DATA: "SET_DAILY_CONTRIBUTION_DATA"
};

export default ActionTypes;
